const Menu = [
  {
    id: 1,
    category: "STARTER",
    image: "images/plain fries.jpg",
    title: "Plain Fries",
    price: 99,
  },
  {
    id: 2,
    category: "STARTER",
    image: "images/garlic mayo.jpg",
    title: "Garlic Mayo Fries",
    price: 150,
  },
  {
    id: 3,
    category: "STARTER",
    image: "images/bbq fries.jpg",
    title: "B.B.Q Fries",
    price: 150,
  },
  {
    id: 4,
    category: "STARTER",
    image: "images/loaded fries.jpg",
    title: "Loaded Fries",
    price: 400,
  },
  {
    id: 5,
    category: "STARTER",
    image: "images/chicken strips.jpg",
    title: "Chicken Strips",
    price: "299 (4pc)",
  },
  {
    id: 6,
    category: "STARTER",
    image: "images/nuggets.jpg",
    title: "Nuggets",
    price: "180 (5pc) 299 (10pc)",
  },
  {
    id: 7,
    category: "BURGERS",
    image: "images/crunch burger.jpg",
    title: "Crunch Burger",
    price: 250,
  },
  {
    id: 8,
    category: "BURGERS",
    image: "images/grilled.jpg",
    title: "Grill of Thrill",
    price: 399,
  },
  {
    id: 9,
    category: "BURGERS",
    image: "images/stuff chicken.jpg",
    title: "Stuff Chicken",
    price: 450,
  },
  {
    id: 10,
    category: "BURGERS",
    image: "images/peri peri burger.jpg",
    title: "Peri peri Chicken",
    price: 399,
  },
  {
    id: 11,
    category: "BURGERS",
    image: "images/mint margreta.jpg",
    title: "Mint Margrita",
    price: 430,
  },
  {
    id: 12,
    category: "BURGERS",
    image: "images/hot dog.jpg",
    title: "Hot Dog Burger",
    price: 250,
  },
  {
    id: 13,
    category: "BURGERS",
    image: "images/grill&bbq.jpg",
    title: "Grill & BBQ Burger",
    price: 410,
  },
  {
    id: 14,
    category: "BURGERS",
    image: "images/chicken patty burger.jpg",
    title: "Chicken Patty Burger",
    price: 250,
  },
  {
    id: 15,
    category: "SANDWICHES",
    image: "images/chicken cheese sandwich.jpg",
    title: "Chicken Cheese Sandwich",
    price: 320,
  },
  {
    id: 16,
    category: "SANDWICHES",
    image: "images/club sandwich.jpg",
    title: "Club Sandwich",
    price: 399,
  },
  {
    id: 17,
    category: "SANDWICHES",
    image: "images/fajita sandwich.jpg",
    title: "Grill Chicken Sandwich",
    price: 350,
  },
  {
    id: 18,
    category: "SANDWICHES",
    image: "images/peri peri sandwich.jpg",
    title: "Peri Peri Sandwich",
    price: 380,
  },
  {
    id: 19,
    category: "SANDWICHES",
    image: "images/crunchy sandwich.jpg",
    title: "Crunchy Sandwich",
    price: 350,
  },
  {
    id: 20,
    category: "WRAP & ROLLS",
    image: "images/bbq wrap.jpg",
    title: "B.B.Q Wrap",
    price: 350,
  },
  {
    id: 21,
    category: "WRAP & ROLLS",
    image: "images/tortila wrap.jpg",
    title: "Cocktail Wrap",
    price: 399,
  },
  {
    id: 22,
    category: "WRAP & ROLLS",
    image: "images/adana kebab wrap.jpg",
    title: "Maxican Wrap",
    price: 350,
  },
  {
    id: 23,
    category: "WRAP & ROLLS",
    image: "images/special wrap.jpg",
    title: "Special Wrap",
    price: 399,
  },
  {
    id: 24,
    category: "WRAP & ROLLS",
    image: "images/chicken shawarma.jpg",
    title: "Chicken Shawarma",
    price: 150,
  },
  {
    id: 25,
    category: "WRAP & ROLLS",
    image: "images/arabian wrap.jpg",
    title: "Arabic Shawarma",
    price: 299,
  },
  {
    id: 26,
    category: "WRAP & ROLLS",
    image: "images/zinger shawarma.jpg",
    title: "Zinger Shawarma",
    price: 199,
  },
  {
    id: 27,
    category: "WRAP & ROLLS",
    image: "images/zinger roll.jpg",
    title: "Zinger Roll",
    price: 350,
  },
  {
    id: 28,
    category: "WRAP & ROLLS",
    image: "images/loaded paratha roll.jpg",
    title: "Loaded Paratha Roll",
    price: 299,
  },

  {
    id: 29,
    category: "WRAP & ROLLS",
    image: "images/chicken paratha roll.jpg",
    title: "Chicken Paratha Roll",
    price: 150,
  },

  {
    id: 30,
    category: "WRAP & ROLLS",
    image: "images/zinger paratha roll.jpg",
    title: "Zinger Paratha Roll",
    price: 199,
  },

  {
    id: 31,
    category: "PASTA",
    image: "images/alfredo.jpg",
    title: "Alfredo Pasta",
    price: 450,
  },
  {
    id: 32,
    category: "PASTA",
    image: "images/baked pasta.jpg",
    title: "Oven Baked Pasta",
    price: 399,
  },
  {
    id: 33,
    category: "PASTA",
    image: "images/maxican pasta.jpg",
    title: "Maxican Pasta",
    price: 350,
  },
  {
    id: 34,
    category: "PIZZA",
    image: "images/supreme pizza.jpg",
    title: "Supreme Pizza",
    price: "299(S) 550(M) 850(L)",
  },
  {
    id: 35,
    category: "PIZZA",
    image: "images/vege pizza.jpg",
    title: "Veggi Lover Pizza",
    price: "299(S) 550(M) 850(L)",
  },
  {
    id: 36,
    category: "PIZZA",
    image: "images/cheese pizza.jpg",
    title: "Cheese Lover Pizza",
    price: "299(S) 550(M) 850(L)",
  },
  {
    id: 37,
    category: "PIZZA",
    image: "images/chicken fajita.jpg",
    title: "Chicken Fajita Pizza",
    price: "299(S) 550(M) 850(L)",
  },
  {
    id: 38,
    category: "PIZZA",
    image: "images/chicken tikka pizza.jpg",
    title: "Chicken Tikka Pizza",
    price: "299(S) 550(M) 850(L)",
  },
  {
    id: 39,
    category: "PIZZA",
    image: "images/super supreme.jpg",
    title: "Super Supreme",
    price: "399(S) 599(M) 899(L)",
  },
  {
    id: 40,
    category: "PIZZA",
    image: "images/kababish pizza.jpg",
    title: "Kababish Pizza",
    price: "399(S) 599(M) 899(L)",
  },
  {
    id: 41,
    category: "PIZZA",
    image: "images/creamy boti pizza.jpg",
    title: "Creamy Boti Pizza",
    price: "399(S) 599(M) 899(L)",
  },
  {
    id: 42,
    category: "PIZZA",
    image: "images/mughlai pizza.jpg",
    title: "Mughlai Pizza",
    price: "299(S) 699(M) 999(L)",
  },
  {
    id: 43,
    category: "PIZZA",
    image: "images/istanbulia special pizza.jpg",
    title: "Istanbulia Special Pizza",
    price: "450(S) 750(M) 1050(L)",
  },
  {
    id: 44,
    category: "NAAN",
    image: "images/pizza naan.jpg",
    title: "Pizza Naan",
    price: "280",
  },
  {
    id: 45,
    category: "NAAN",
    image: "images/bbq naan.jpg",
    title: "B.B.Q Naan",
    price: "280",
  },
  {
    id: 46,
    category: "NAAN",
    image: "images/smoked chicken naan.jpg",
    title: "Smoked Chicken Naan",
    price: "280",
  },
  {
    id: 47,
    category: "NAAN",
    image: "images/cheese naan.jpg",
    title: "Cheese Naan",
    price: "299",
  },
  {
    id: 48,
    category: "NAAN",
    image: "images/veg cheese naan.jpg",
    title: "Veggi cheese Naan",
    price: "250",
  },
  {
    id: 49,
    category: "NAAN",
    image: "images/butter garlic naan.jpg",
    title: "Butter Garlic Naan",
    price: "299",
  },
];

export default Menu;